Repository nmshd/connector, pull requests merged in 2024-12, with the labels that each got.

#320 Password-protection
  .dev/appsettings.override.json
  .dev/compose.backbone.env
  package-lock.json
  package.json
  packages/sdk/package.json
  packages/sdk/src/types/files/requests/CreateTokenForFileRequest.ts
  packages/sdk/src/types/files/requests/CreateTokenQrCodeForFileRequest.ts
  packages/sdk/src/types/files/requests/LoadPeerFileRequest.ts
  packages/sdk/src/types/relationshipTemplates/ConnectorRelationshipTemplate.ts
  packages/sdk/src/types/relationshipTemplates/requests/CreateOwnRelationshipTemplateRequest.ts
  packages/sdk/src/types/relationshipTemplates/requests/CreateTokenForOwnRelationshipTemplateRequest.ts
  packages/sdk/src/types/relationshipTemplates/requests/CreateTokenQrCodeForOwnRelationshipTemplateRequest.ts
  packages/sdk/src/types/relationshipTemplates/requests/LoadPeerRelationshipTemplateRequest.ts
  packages/sdk/src/types/tokens/ConnectorToken.ts
  packages/sdk/src/types/tokens/requests/CreateOwnTokenRequest.ts
  packages/sdk/src/types/tokens/requests/LoadPeerTokenRequest.ts
  src/modules/coreHttpApi/controllers/FilesController.ts
  src/modules/coreHttpApi/controllers/RelationshipTemplatesController.ts
  src/modules/coreHttpApi/openapi.yml
  test/attributes.test.ts
  test/files.test.ts
  test/lib/testUtils.ts
  test/relationshipTemplates.test.ts
  test/tokens.test.ts
Labels: enhancement

#324 Update dependencies
  package-lock.json
  package.json
  packages/sdk/package.json
Labels: dependencies

#327 Query password protection
  package-lock.json
  package.json
  packages/sdk/package.json
  packages/sdk/src/types/relationshipTemplates/requests/GetOwnRelationshipTemplatesRequest.ts
  packages/sdk/src/types/relationshipTemplates/requests/GetPeerRelationshipTemplatesRequest.ts
  packages/sdk/src/types/relationshipTemplates/requests/GetRelationshipTemplatesRequest.ts
  packages/sdk/src/types/tokens/requests/GetOwnTokensRequest.ts
  packages/sdk/src/types/tokens/requests/GetPeerTokensRequest.ts
  src/modules/coreHttpApi/openapi.yml
  test/relationshipTemplates.test.ts
  test/tokens.test.ts
Labels: enhancement

#332 Utf8 in filename is encoded as latin1
  src/modules/coreHttpApi/controllers/FilesController.ts
  test/files.test.ts
Labels: bug

#333 Allow uploading empty files
  package-lock.json
  package.json
  packages/sdk/package.json
  src/modules/coreHttpApi/common/BaseController.ts
  test/files.test.ts
Labels: enhancement
