Repository nmshd/connector, pull requests merged in 2024-06, with the labels that each got.

#170 Release using GitHub releases
  .ci/buildAndPush.sh
  .ci/publishHelmChart.sh
  .ci/publishNpm.sh
  .ci/testBuildingProductiveDockerImage.sh
  .ci/writeBuildInformation.sh
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yml
  .github/release.yml
  .github/workflows/check-pr.yml
  .github/workflows/publish.yml
  .github/workflows/version-check.yml
  .nvmrc
  CHANGELOG.md
  Dockerfile
  package-lock.json
  package.json
  packages/sdk/package.json
Labels: ci

#171 Update dependabot.yml
  .github/dependabot.yml
Labels: ci

#172 Update dependabot.yml
  .github/dependabot.yml
Labels: ci

#174 Remove deprecated features
  config/default.json
  src/index.ts
  src/modules/amqpPublisher/AMQPPublisherModule.ts
  src/modules/coreHttpApi/controllers/AttributesController.ts
  src/modules/pubSubPublisher/PubSubPublisherModule.ts
Labels: breaking-change

#166 Implement the new Relationship API
  .dev/appsettings.override.json
  .dev/compose.backbone.env
  .gitignore
  package-lock.json
  package.json
  packages/sdk/src/endpoints/AttributesEndpoint.ts
  packages/sdk/src/endpoints/Endpoint.ts
  packages/sdk/src/endpoints/RelationshipsEndpoint.ts
  packages/sdk/src/types/ConnectorResponse.ts
  packages/sdk/src/types/relationships/ConnectorIdentity.ts
  packages/sdk/src/types/relationships/ConnectorRelationship.ts
  packages/sdk/src/types/relationships/ConnectorRelationshipAuditLogEntry.ts
  packages/sdk/src/types/relationships/ConnectorRelationshipAuditLogEntryReason.ts
  packages/sdk/src/types/relationships/ConnectorRelationshipChange.ts
  packages/sdk/src/types/relationships/ConnectorRelationshipChangeRequest.ts
  packages/sdk/src/types/relationships/ConnectorRelationshipChangeResponse.ts
  packages/sdk/src/types/relationships/ConnectorRelationshipChangeStatus.ts
  packages/sdk/src/types/relationships/ConnectorRelationshipChangeType.ts
  packages/sdk/src/types/relationships/ConnectorRelationshipChanges.ts
  packages/sdk/src/types/relationships/ConnectorRelationshipStatus.ts
  packages/sdk/src/types/relationships/index.ts
  packages/sdk/src/types/relationships/requests/CreateRelationshipRequest.ts
  src/ConnectorRuntime.ts
  src/infrastructure/ConnectorInfrastructureRegistry.ts
  src/infrastructure/httpServer/common/HttpError.ts
  src/infrastructure/httpServer/middlewares/genericErrorHandler.ts
  src/modules/autoAcceptRelationshipCreationChanges/AutoAcceptRelationshipCreationChangesModule.ts
  src/modules/coreHttpApi/controllers/AttributesController.ts
  src/modules/coreHttpApi/controllers/RelationshipsController.ts
  src/modules/coreHttpApi/openapi.yml
  test/attributes.test.ts
  test/compose.yml
  test/iqlquery.test.ts
  test/lib/MockEventBus.ts
  test/lib/QueryParamConditions.ts
  test/lib/customMatcher.ts
  test/lib/testUtils.ts
  test/messages.test.ts
  test/outgoingRequests.test.ts
  test/relationships.test.ts
  test/spec.test.ts
Labels: breaking-change

#192 Fix/network errors were treated as application errors
  .gitignore
  src/infrastructure/httpServer/middlewares/genericErrorHandler.ts
Labels: bug

#193 Chore/Fix vulnerability
  package-lock.json
  package.json
Labels: chore

#194 Merge/main->v5
  .dev/Dockerfile.debug
  .gitignore
  Dockerfile
  package-lock.json
  package.json
  src/infrastructure/httpServer/middlewares/genericErrorHandler.ts
Labels: chore

#196 Chore/audit fix
  package-lock.json
Labels: chore
