Repository nmshd/connector, pull requests merged in 2024-09, with the labels that each got.

#248 Update openapi.yml with correct values for `POST /api/v2/Attributes`
  package-lock.json
  packages/sdk/src/endpoints/AttributesEndpoint.ts
  packages/sdk/src/types/attributes/index.ts
  packages/sdk/src/types/attributes/requests/GetSharedVersionsOfAttributeRequest.ts
  packages/sdk/src/types/attributes/requests/GetSharedVersionsOfRepositoryAttributeRequest.ts
  src/modules/coreHttpApi/openapi.yml
Labels: bug

#250 Dependabot: exclude libraries that have to be bumped as a group
  .github/dependabot.yml
Labels: ci

#252 Bump dependencies
  package-lock.json
  package.json
  packages/sdk/package.json
Labels: dependencies

#258 Ignore codecov upload issues
  .ci/runChecks.sh
  .github/workflows/test.yml
Labels: ci

#261 Group runtime Dependabot updates
  .github/dependabot.yml
Labels: ci

#265 Cleanup the connector config
  .ci/runChecks.sh
  config/default.json
  src/ConnectorRuntimeConfig.ts
  src/jsonSchemas/connectorConfig.json
  src/jsonSchemas/connectorConfig.ts
Labels: chore

#269 Remove object loading by id and key
  package-lock.json
  package.json
  packages/sdk/package.json
  packages/sdk/src/endpoints/FilesEndpoint.ts
  packages/sdk/src/endpoints/RelationshipTemplatesEndpoint.ts
  packages/sdk/src/endpoints/TokensEndpoint.ts
  packages/sdk/src/types/files/ConnectorFile.ts
  packages/sdk/src/types/files/FileReference.ts
  packages/sdk/src/types/files/TruncatedFileReference.ts
  packages/sdk/src/types/files/index.ts
  packages/sdk/src/types/files/requests/LoadPeerFileRequest.ts
  packages/sdk/src/types/relationshipTemplates/ConnectorRelationshipTemplate.ts
  packages/sdk/src/types/relationshipTemplates/RelationshipTemplateReference.ts
  packages/sdk/src/types/relationshipTemplates/TruncatedRelationshipTemplateReference.ts
  packages/sdk/src/types/relationshipTemplates/index.ts
  packages/sdk/src/types/relationshipTemplates/requests/LoadPeerRelationshipTemplateRequest.ts
  packages/sdk/src/types/tokens/ConnectorToken.ts
  packages/sdk/src/types/tokens/TokenReference.ts
  packages/sdk/src/types/tokens/TokenReferenceTruncated.ts
  packages/sdk/src/types/tokens/index.ts
  packages/sdk/src/types/tokens/requests/LoadPeerTokenRequest.ts
  src/modules/coreHttpApi/openapi.yml
  test/files.test.ts
Labels: breaking-change

#222 Add correlation to all requests and the logger
  .dev/compose.backbone.env
  config/default.json
  config/test.json
  package-lock.json
  package.json
  src/ConnectorRuntime.ts
  src/index.ts
  src/infrastructure/httpServer/HttpServer.ts
  src/modules/sse/SseModule.ts
  src/modules/sync/SyncModule.ts
  src/modules/webhooks/WebhooksModule.ts
  test/correlationId.test.ts
  test/lib/DataEventWithHeader.ts
  test/lib/Launcher.ts
  test/lib/MockEventBus.ts
Labels: enhancement

#273 Logs can not be written
  config/default.json
Labels: bug
