Repository nmshd/connector, pull requests merged in 2024-11, with the labels that each got.

#305 Make `creationContent` parameter of CanCreateRelationship API route optional
  package-lock.json
  package.json
  packages/sdk/package.json
  packages/sdk/src/endpoints/RelationshipsEndpoint.ts
  packages/sdk/src/types/relationships/index.ts
  packages/sdk/src/types/relationships/requests/CanCreateRelationshipRequest.ts
  src/modules/coreHttpApi/openapi.yml
  test/relationships.test.ts
Labels: enhancement

#307 `@type` is displayed as required in `onNewRelationship`
  src/modules/coreHttpApi/openapi.yml
Labels: bug

#306 Warn about a weak API-Key at startup
  .dev/compose.prodtest.yml
  .dev/config.json
  .dev/scripts/establishRelationshipAndSpamMessages.ts
  .dev/scripts/syncConnector1.sh
  .dev/scripts/syncConnector2.sh
  README_dev.md
  src/infrastructure/httpServer/HttpServer.ts
  test/errors.test.ts
  test/lib/Launcher.ts
Labels: enhancement

#309 Some objects in the OpenAPI spec are incorrect
  src/modules/coreHttpApi/openapi.yml
Labels: bug

#293 Personalized RelationshipTemplates
  .dev/compose.backbone.env
  packages/sdk/src/types/relationshipTemplates/ConnectorRelationshipTemplate.ts
  packages/sdk/src/types/relationshipTemplates/requests/CreateOwnRelationshipTemplateRequest.ts
  packages/sdk/src/types/relationshipTemplates/requests/CreateTokenForOwnRelationshipTemplateRequest.ts
  packages/sdk/src/types/relationshipTemplates/requests/CreateTokenQrCodeForOwnRelationshipTemplateRequest.ts
  packages/sdk/src/types/relationshipTemplates/requests/GetOwnRelationshipTemplatesRequest.ts
  packages/sdk/src/types/relationshipTemplates/requests/GetPeerRelationshipTemplatesRequest.ts
  packages/sdk/src/types/relationshipTemplates/requests/GetRelationshipTemplatesRequest.ts
  packages/sdk/src/types/tokens/ConnectorToken.ts
  src/modules/coreHttpApi/controllers/RelationshipTemplatesController.ts
  src/modules/coreHttpApi/openapi.yml
  test/lib/testUtils.ts
  test/relationshipTemplates.test.ts
Labels: enhancement

#294 Personalized Tokens
  packages/sdk/src/types/files/requests/CreateTokenForFileRequest.ts
  packages/sdk/src/types/files/requests/CreateTokenQrCodeForFileRequest.ts
  packages/sdk/src/types/tokens/requests/CreateOwnTokenRequest.ts
  packages/sdk/src/types/tokens/requests/GetOwnTokensRequest.ts
  packages/sdk/src/types/tokens/requests/GetPeerTokensRequest.ts
  src/modules/coreHttpApi/controllers/FilesController.ts
  src/modules/coreHttpApi/openapi.yml
  test/files.test.ts
  test/lib/testUtils.ts
  test/relationshipTemplates.test.ts
  test/tokens.test.ts
Labels: enhancement

#310 Add identity deletion debug APIs
  src/modules/coreHttpApi/CoreHttpApiModule.ts
  src/modules/coreHttpApi/debug-controllers/IdentityDeletionController.ts
  test/debug/identityDeletionProcess.test.ts
  test/lib/Launcher.ts
  test/spec.test.ts
Labels: chore

#312 Update naming convention
  .eslintrc
  packages/sdk/src/ConnectorClient.ts
  src/modules/webhooks/WebhooksModule.ts
  test/correlationId.test.ts
  test/errors.test.ts
Labels: chore
