Repository nmshd/connector, pull requests merged in 2024-08, with the labels that each got.

#224 Restrict either the SSE or the Sync module to be active but not both
  src/index.ts
Labels: chore

#229 Fix socket hangups during debugging of tests
  test/lib/Launcher.ts
Labels: enhancement

#230 Add code coverage to tests
  .github/workflows/test.yml
  .gitignore
  package-lock.json
  package.json
  test/iqlquery.test.ts
Labels: test

#232 Add tests for coverage on main branch
  .github/workflows/test.yml
Labels: chore

#223 Return 204 from the Sync Route
  packages/sdk/src/endpoints/AccountEndpoint.ts
  packages/sdk/src/types/account/ConnectorSyncResult.ts
  packages/sdk/src/types/account/index.ts
  packages/sdk/src/types/messages/ConnectorMessageRecipient.ts
  src/modules/coreHttpApi/controllers/AccountController.ts
  src/modules/coreHttpApi/openapi.yml
  test/account.test.ts
  test/attributes.test.ts
  test/iqlquery.test.ts
  test/lib/testUtils.ts
  test/lib/validation.ts
  test/relationships.test.ts
  test/spec.test.ts
Labels: breaking-change

#236 Upgrade runtime
  .ci/runChecks.sh
  .github/workflows/test.yml
  package-lock.json
  package.json
  packages/sdk/package.json
  packages/sdk/src/types/attributes/ConnectorAttribute.ts
  packages/sdk/src/types/attributes/requests/GetOwnRepositoryAttributesRequest.ts
  packages/sdk/src/types/attributes/requests/GetOwnSharedIdentityAttributesRequest.ts
  packages/sdk/src/types/attributes/requests/GetPeerSharedIdentityAttributesRequest.ts
Labels: dependencies, runtime-upgrade

#227 Upgrade runtime
  .dev/compose.backbone.env
  .dev/compose.backbone.yml
  .dev/scripts/establishRelationshipAndSpamMessages.ts
  package-lock.json
  package.json
  packages/sdk/_examples/relationships.ts
  packages/sdk/src/endpoints/AccountEndpoint.ts
  packages/sdk/src/endpoints/AttributesEndpoint.ts
  packages/sdk/src/endpoints/ChallengesEndpoint.ts
  packages/sdk/src/endpoints/Endpoint.ts
  packages/sdk/src/endpoints/FilesEndpoint.ts
  packages/sdk/src/endpoints/IncomingRequestsEndpoint.ts
  packages/sdk/src/endpoints/MessagesEndpoint.ts
  packages/sdk/src/endpoints/OutgoingRequestsEndpoint.ts
  packages/sdk/src/endpoints/RelationshipTemplatesEndpoint.ts
  packages/sdk/src/endpoints/RelationshipsEndpoint.ts
  packages/sdk/src/endpoints/TokensEndpoint.ts
  packages/sdk/src/types/ConnectorHttpResponse.ts
  packages/sdk/src/types/attributes/ConnectorAttribute.ts
  packages/sdk/src/types/index.ts
  packages/sdk/src/types/messages/ConnectorMessage.ts
  packages/sdk/src/types/messages/ConnectorMessageContentDerivation.ts
  packages/sdk/src/types/messages/ConnectorMessageWithAttachments.ts
  packages/sdk/src/types/messages/requests/SendMessageRequest.ts
  packages/sdk/src/types/notifications/ConnectorNotification.ts
  packages/sdk/src/types/notifications/ConnectorNotificationItem.ts
  packages/sdk/src/types/notifications/index.ts
  packages/sdk/src/types/relationshipTemplates/ConnectorRelationshipTemplate.ts
  packages/sdk/src/types/relationshipTemplates/ConnectorRelationshipTemplateContentDerivation.ts
  packages/sdk/src/types/relationshipTemplates/index.ts
  packages/sdk/src/types/relationshipTemplates/requests/CreateOwnRelationshipTemplateRequest.ts
  packages/sdk/src/types/relationships/ConnectorRelationship.ts
  packages/sdk/src/types/relationships/ConnectorRelationshipCreationContentDerivation.ts
  packages/sdk/src/types/relationships/index.ts
  packages/sdk/src/types/relationships/requests/AcceptRelationshipChangeRequest.ts
  packages/sdk/src/types/relationships/requests/CreateRelationshipRequest.ts
  packages/sdk/src/types/relationships/requests/RejectRelationshipChangeRequest.ts
  packages/sdk/src/types/requests/ConnectorRequest.ts
  packages/sdk/src/types/requests/ConnectorRequestContent.ts
  packages/sdk/src/types/requests/ConnectorResponse.ts
  packages/sdk/src/types/requests/index.ts
  packages/sdk/src/types/requests/requests/CreateOutgoingRequestRequest.ts
  src/modules/coreHttpApi/openapi.yml
  test/attributes.test.ts
  test/iqlquery.test.ts
  test/lib/QueryParamConditions.ts
  test/lib/testUtils.ts
  test/lib/validation.ts
  test/messages.test.ts
  test/relationshipTemplates.test.ts
  test/relationships.test.ts
  test/spec.test.ts
Labels: dependencies, runtime-upgrade

#239 AutoAcceptPendingRelationshipsModule not found
  src/modules/autoAcceptPendingRelationships/AutoAcceptPendingRelationshipsModule.ts
Labels: bug

#241 Add AutoDecomposeDeletionProposedRelationships Module
  .ci/runChecks.sh
  config.schema.json
  config/default.json
  package-lock.json
  src/ConnectorRuntime.ts
  src/modules/autoAcceptPendingRelationships/AutoAcceptPendingRelationshipsModule.ts
  src/modules/autoDecomposeDeletionProposedRelationships/AutoDecomposeDeletionProposedRelationshipsModule.ts
  src/modules/sync/SyncModule.ts
Labels: enhancement

#238 Update openAPI spec
  src/modules/coreHttpApi/openapi.yml
Labels: documentation

#242 Remove enmeshed-prod as default backbone
  Dockerfile
  config/prod.json
Labels: breaking-change

#240 Adjust to new consumptionConfig to disable setting default RepositoryAttributes
  package-lock.json
  package.json
  src/ConnectorRuntime.ts
  test/attributes.test.ts
Labels: enhancement

#247 Update Runtime
  .ci/runChecks.sh
  package-lock.json
  package.json
  packages/sdk/_examples/messages.ts
  packages/sdk/package.json
  packages/sdk/src/types/attributes/ConnectorAttribute.ts
  packages/sdk/src/types/attributes/requests/CreateRepositoryAttributeRequest.ts
  packages/sdk/src/types/attributes/requests/SucceedAttributeRequest.ts
  packages/sdk/src/types/messages/ConnectorMessage.ts
  packages/sdk/src/types/messages/ConnectorMessageContentDerivation.ts
  packages/sdk/src/types/messages/ConnectorMessageWithAttachments.ts
  packages/sdk/src/types/messages/requests/SendMessageRequest.ts
  packages/sdk/src/types/relationshipTemplates/ConnectorRelationshipTemplate.ts
  packages/sdk/src/types/relationshipTemplates/ConnectorRelationshipTemplateContentDerivation.ts
  packages/sdk/src/types/relationshipTemplates/index.ts
  packages/sdk/src/types/relationshipTemplates/requests/CreateOwnRelationshipTemplateRequest.ts
  packages/sdk/src/types/relationships/ConnectorPeerDeletionInfo.ts
  packages/sdk/src/types/relationships/ConnectorRelationship.ts
  packages/sdk/src/types/relationships/ConnectorRelationshipCreationContentDerivation.ts
  packages/sdk/src/types/relationships/index.ts
  packages/sdk/src/types/relationships/requests/CreateRelationshipRequest.ts
  packages/sdk/src/types/requests/ConnectorRequest.ts
  packages/sdk/src/types/requests/ConnectorRequestContent.ts
  packages/sdk/src/types/requests/ConnectorResponse.ts
  packages/sdk/src/types/requests/index.ts
  packages/sdk/src/types/requests/requests/CreateOutgoingRequestRequest.ts
  src/ConnectorRuntime.ts
  src/HealthChecker.ts
  src/infrastructure/httpServer/middlewares/genericErrorHandler.ts
  test/attributes.test.ts
  test/iqlquery.test.ts
  test/lib/testUtils.ts
  test/outgoingRequests.test.ts
  test/relationships.test.ts
Labels: dependencies, refactoring
