Repository nmshd/connector, pull requests merged in 2024-10, with the labels that each got.

#276 Decompose relationships at connector startup in AutoDecomposeDeletionProposedRelationshipsModule
  src/modules/autoDecomposeDeletionProposedRelationships/AutoDecomposeDeletionProposedRelationshipsModule.ts
Labels: enhancement

#279 Add deletionDate to Relationship's peerDeletionInfo
  package-lock.json
  package.json
  packages/sdk/package.json
  packages/sdk/src/types/relationships/ConnectorPeerDeletionInfo.ts
  src/modules/coreHttpApi/openapi.yml
Labels: enhancement

#280 Use node current for checks in pipelines
  .github/workflows/publish.yml
  .github/workflows/test.yml
Labels: ci

#282 Chore/bump runtime to 6.3.0
  .ci/runChecks.sh
  package-lock.json
  package.json
  packages/sdk/package.json
  src/HealthChecker.ts
  src/infrastructure/httpServer/HttpServer.ts
  src/infrastructure/httpServer/middlewares/setResponseDurationHeader.ts
  src/infrastructure/httpServer/middlewares/setResponseTimeHeader.ts
  src/modules/coreHttpApi/CoreHttpApiModule.ts
  test/messages.test.ts
Labels: dependencies

#283 Use `@nmshd/typescript-ioc` and `@nmshd/typescript-rest` to get rid of vulnerabilities
  .ci/runChecks.sh
  package-lock.json
  package.json
  packages/sdk/package.json
  src/infrastructure/httpServer/HttpServer.ts
  src/infrastructure/httpServer/middlewares/genericErrorHandler.ts
  src/modules/coreHttpApi/common/BaseController.ts
  src/modules/coreHttpApi/controllers/AccountController.ts
  src/modules/coreHttpApi/controllers/AttributesController.ts
  src/modules/coreHttpApi/controllers/ChallengesController.ts
  src/modules/coreHttpApi/controllers/FilesController.ts
  src/modules/coreHttpApi/controllers/IncomingRequestsController.ts
  src/modules/coreHttpApi/controllers/MessagesController.ts
  src/modules/coreHttpApi/controllers/OutgoingRequestsController.ts
  src/modules/coreHttpApi/controllers/RelationshipTemplatesController.ts
  src/modules/coreHttpApi/controllers/RelationshipsController.ts
  src/modules/coreHttpApi/controllers/TokensController.ts
  test/spec.test.ts
Labels: dependencies

#285 Mixed up properties in OpenAPI schemas
  src/modules/coreHttpApi/openapi.yml
Labels: bug

#284 Add backbone compatibility check on startup
  package-lock.json
  packages/sdk/package.json
  src/ConnectorRuntime.ts
Labels: enhancement

#291 Downgrade Node.js
  .github/workflows/publish.yml
  .github/workflows/test.yml
Labels: ci

#290 Simplify code
  src/modules/autoAcceptPendingRelationships/AutoAcceptPendingRelationshipsModule.ts
  src/modules/autoDecomposeDeletionProposedRelationships/AutoDecomposeDeletionProposedRelationshipsModule.ts
Labels: chore

#292 Add CanCreateRelationship API route
  package-lock.json
  package.json
  packages/sdk/package.json
  packages/sdk/src/endpoints/AttributesEndpoint.ts
  packages/sdk/src/endpoints/RelationshipsEndpoint.ts
  packages/sdk/src/types/attributes/ConnectorAttribute.ts
  packages/sdk/src/types/attributes/index.ts
  packages/sdk/src/types/attributes/requests/DeleteThirdPartyOwnedRelationshipAttributeAndNotifyPeerResponse.ts
  packages/sdk/src/types/attributes/requests/DeleteThirdPartyRelationshipAttributeAndNotifyPeerResponse.ts
  packages/sdk/src/types/attributes/requests/GetAttributesRequest.ts
  packages/sdk/src/types/attributes/requests/GetOwnSharedIdentityAttributesRequest.ts
  packages/sdk/src/types/attributes/requests/GetPeerSharedIdentityAttributesRequest.ts
  packages/sdk/src/types/relationships/index.ts
  packages/sdk/src/types/relationships/responses/CanCreateRelationshipResponse.ts
  src/ConnectorRuntimeConfig.ts
  src/modules/coreHttpApi/controllers/AttributesController.ts
  src/modules/coreHttpApi/controllers/RelationshipsController.ts
  src/modules/coreHttpApi/openapi.yml
  test/attributes.test.ts
  test/relationships.test.ts
Labels: enhancement

#300 Change GmbH to AG
  LICENSE
  helmChart/LICENSE
  package.json
  packages/sdk/LICENSE
  packages/sdk/package.json
  src/modules/coreHttpApi/openapi.yml
Labels: chore

#301 Add IdentityMetadata Routes
  packages/sdk/src/ConnectorClient.ts
  packages/sdk/src/endpoints/IdentityMetadataEndpoint.ts
  packages/sdk/src/endpoints/index.ts
  packages/sdk/src/types/identityMetadata/ConnectorIdentityMetadata.ts
  packages/sdk/src/types/identityMetadata/index.ts
  packages/sdk/src/types/identityMetadata/requests/UpsertIdentityMetadataRequest.ts
  packages/sdk/src/types/index.ts
  src/modules/coreHttpApi/controllers/IdentityMetadataController.ts
  src/modules/coreHttpApi/openapi.yml
  test/identityMetadata.test.ts
  test/lib/validation.ts
  test/spec.test.ts
Labels: enhancement

#295 TLS Certificate Pinning and Force TLS Checks
  src/ConnectorRuntime.ts
  src/ConnectorRuntimeConfig.ts
  src/index.ts
  src/jsonSchemas/connectorConfig.json
  src/jsonSchemas/connectorConfig.ts
Labels: enhancement

#286 Convert connector to CLI
  .dev/Dockerfile.debug
  .dev/compose.prodtest.yml
  .vscode/tasks.json
  Dockerfile
  README_dev.md
  package-lock.json
  package.json
  src/ConnectorRuntime.ts
  src/CreateConnectorConfig.ts
  src/cli/BaseCommand.ts
  src/cli/commands/index.ts
  src/cli/commands/startConnector.ts
  src/index.ts
  test/lib/Launcher.ts
Labels: refactoring

#303 Re-add resolved and integrity to lockfile
  package-lock.json
  package.json
  packages/sdk/package.json
  packages/sdk/src/endpoints/Endpoint.ts
Labels: chore
