Repository nmshd/connector, pull requests merged in 2024-07, with the labels that each got.

#197 Allow skipping the tls check for webhooks
  src/modules/messageBrokerPublisher/connectors/MessageBrokerConnector.ts
  src/modules/webhooks/ConfigModel.ts
  src/modules/webhooks/ConfigParser.ts
  src/modules/webhooks/WebhooksModule.ts
  src/modules/webhooks/WebhooksModuleConfiguration.ts
Labels: enhancement

#199 Upgrade local backbone version
  .dev/appsettings.override.json
  .dev/compose.backbone.env
Labels: chore

#200 Upgrade local backbone version
  .dev/appsettings.override.json
  .dev/compose.backbone.env
Labels: chore

#201 Chore/Enable host-gateway dns on linux docker
  .dev/compose.yml
Labels: chore

#203 Upgrade dependencies
  package-lock.json
  package.json
  test/attributes.test.ts
  test/spec.test.ts
Labels: dependencies

#191 Add new termination and reactivation routes
  config.schema.json
  config/default.json
  package-lock.json
  package.json
  packages/sdk/src/endpoints/RelationshipsEndpoint.ts
  packages/sdk/src/types/relationships/ConnectorRelationshipAuditLogEntryReason.ts
  src/modules/autoAcceptPendingRelationships/AutoAcceptPendingRelationships.ts
  src/modules/coreHttpApi/controllers/RelationshipsController.ts
  src/modules/coreHttpApi/openapi.yml
  test/lib/validation.ts
  test/relationships.test.ts
Labels: enhancement

#210 Fix missing wait for event
  test/attributes.test.ts
Labels: test

#205 Refactoring/remove mustbeaccepted of requestitemgroup
  package-lock.json
  package.json
  packages/sdk/src/types/requests/ConnectorRequestContent.ts
  src/modules/coreHttpApi/openapi.yml
  test/outgoingRequests.test.ts
Labels: refactoring

#207 Add script to copy local runtime
  .dev/scripts/linkRuntime.sh
  README_dev.md
  package.json
Labels: chore

#206 Test would not stop when there is an error in the connector startup
  test/lib/Launcher.ts
  test/lib/waitForConnector.ts
Labels: test

#211 Upgrade nodejs base image to version 22.4.1
  .dev/Dockerfile.debug
  Dockerfile
Labels: chore

#212 Relationship decomposition
  .dev/compose.backbone.env
  package-lock.json
  package.json
  packages/sdk/src/endpoints/AttributesEndpoint.ts
  packages/sdk/src/endpoints/Endpoint.ts
  packages/sdk/src/endpoints/RelationshipsEndpoint.ts
  packages/sdk/src/types/relationships/ConnectorRelationshipAuditLogEntryReason.ts
  packages/sdk/src/types/relationships/ConnectorRelationshipStatus.ts
  src/modules/coreHttpApi/controllers/AttributesController.ts
  src/modules/coreHttpApi/controllers/RelationshipsController.ts
  src/modules/coreHttpApi/openapi.yml
  test/attributes.test.ts
  test/lib/testUtils.ts
  test/lib/validation.ts
  test/relationships.test.ts
  test/spec.test.ts
Labels: enhancement

#176 Add server sent events module
  .dev/.env.example
  .dev/.env.local
  .dev/appsettings.override.json
  .dev/compose.backbone.yml
  .dev/compose.yml
  .dev/config.json
  .dev/scripts/clearDb.ts
  .dev/scripts/establishRelationshipAndSpamMessages.ts
  .vscode/tasks.json
  config/default.json
  package-lock.json
  package.json
  src/ConnectorRuntime.ts
  src/modules/sse/SseModule.ts
  test/compose.yml
Labels: enhancement

#214 Upgrade the Runtime
  package-lock.json
  package.json
Labels: dependencies

#215 DeleteAttributeRequestItem is missing in SDK
  packages/sdk/src/types/requests/ConnectorRequestContent.ts
Labels: bug

#216 Allow addressGenerationHostnameOverride in config
  .dev/.env.local
  .dev/compose.yml
  package-lock.json
  package.json
  src/jsonSchemas/connectorConfig.json
  src/jsonSchemas/connectorConfig.ts
Labels: bug

#220 Change DocumentationLink for errorCodes
  src/DocumentationLink.ts
  test/errors.test.ts
Labels: documentation
