Repository nmshd/connector, pull requests merged in 2025-02, with the labels that each got.

#362 Add CanCreateRepositoryAttribute
  .dev/appsettings.override.json
  .dev/compose.backbone.env
  .dev/compose.backbone.yml
  package-lock.json
  package.json
  packages/sdk/package.json
  packages/sdk/src/endpoints/AttributesEndpoint.ts
  packages/sdk/src/types/attributes/index.ts
  packages/sdk/src/types/attributes/requests/CanCreateRepositoryAttributeRequest.ts
  packages/sdk/src/types/attributes/requests/CanCreateRepositoryAttributeResponse.ts
  src/modules/coreHttpApi/controllers/AttributesController.ts
  src/modules/coreHttpApi/openapi.yml
  test/attributes.test.ts
Labels: enhancement

#363 Connector does not start in kubernetes
  .dev/Dockerfile.debug
  .dev/compose.prodtest.yml
  .dev/compose.yml
  README_dev.md
  helmChart/README.md
  helmChart/values.yaml
  src/infrastructure/httpServer/HttpServer.ts
Labels: bug

#365 Connector does not start on kubernetes
  .dev/Dockerfile.debug
  .dev/compose.prodtest.yml
  .dev/compose.yml
  README_dev.md
  helmChart/README.md
  helmChart/templates/NOTES.txt
  helmChart/templates/deployment.yaml
  helmChart/values.yaml
  src/healthcheck.ts
  src/infrastructure/httpServer/HttpServer.ts
Labels: bug

#369 Simplify config setup
  .dev/test.json
  Dockerfile
  config/default.json
  src/CreateConnectorConfig.ts
  src/cli/BaseCommand.ts
  src/cli/commands/startConnector.ts
  src/createConnectorConfig.ts
  src/healthcheck.ts
  test/lib/Launcher.ts
  test/modules/cli/setup.ts
Labels: refactoring

#366 Add a zipped version of the built connector to any release
  .ci/buildConnectorZip.sh
  .ci/writeBuildInformation.sh
  .dockerignore
  .github/workflows/publish.yml
Labels: ci

#370 Do not publish mapping files to image or zip
  .ci/buildConnectorZip.sh
  Dockerfile
  package.json
  tsconfig.publish.json
Labels: ci

#372 Monitoring types are not exported from the SDK
  packages/sdk/src/types/index.ts
Labels: bug

#378 Connector installs and starts under old NodeJS without a warning
  package-lock.json
  package.json
Labels: bug
