Repository nmshd/connector, pull requests merged in 2025-07, with the labels that each got.

#281 Add configuration option to disable automatic identity creation
  .dev/config.json
  .dev/test.json
  src/createConnectorConfig.ts
  src/jsonSchemas/connectorConfig.json
  src/jsonSchemas/connectorConfig.ts
Labels: enhancement

#554 The non existing module AttributeListenerModule is enabled
  src/ConnectorRuntime.ts
  src/createConnectorConfig.ts
Labels: bug

#557 An error during storing secrets will destroy the created identity
  package-lock.json
  package.json
  packages/sdk/package.json
  packages/types/package.json
Labels: bug

#561 Mimetype regex is crashing the swagger parser
  src/modules/coreHttpApi/openapi.yml
Labels: bug

#563 Remove apiKey field from ConnectorClientConfig
  .dev/scripts/establishRelationshipAndSpamMessages.ts
  packages/sdk/README.md
  packages/sdk/src/ConnectorClient.ts
  packages/sdk/src/ConnectorClientConfig.ts
Labels: breaking-change

#581 Update `openapi.yml`
  src/modules/coreHttpApi/openapi.yml
Labels: chore

#584 Having no subcommand is not giving a help
  src/index.ts
Labels: bug
