Repository nmshd/connector, pull requests merged in 2025-05, with the labels that each got.

#430 The Webhooks Module configuration is not named properly
  src/modules/webhooks/ConfigModel.ts
  src/modules/webhooks/ConfigParser.ts
  src/modules/webhooks/WebhooksModule.ts
  src/modules/webhooks/WebhooksModuleApplicationErrors.ts
  src/modules/webhooks/WebhooksModuleConfiguration.ts
  src/modules/webhooks/authentication/ApiKeyTargetAuthenticator.ts
  src/modules/webhooks/authentication/OAuth2TargetAuthenticator.ts
  src/modules/webhooks/authentication/TargetAuthenticator.ts
  src/modules/webhooks/authentication/index.ts
Labels: bug

#431 Queries for Get*AttributeRequests are not properly typed and tested
  packages/sdk/src/types/attributes/requests/GetOwnSharedIdentityAttributesRequest.ts
  packages/sdk/src/types/attributes/requests/GetPeerSharedIdentityAttributesRequest.ts
  test/attributes.test.ts
Labels: bug

#432 Add ncurc.json
  .ncurc.json
Labels: chore

#419 Bump express
  package-lock.json
  package.json
  packages/types/package.json
  src/modules/coreHttpApi/CoreHttpApiModule.ts
  src/modules/coreHttpApi/controllers/AttributesController.ts
  src/modules/coreHttpApi/controllers/FilesController.ts
  src/modules/coreHttpApi/controllers/IncomingRequestsController.ts
  src/modules/coreHttpApi/controllers/MessagesController.ts
  src/modules/coreHttpApi/controllers/OutgoingRequestsController.ts
  src/modules/coreHttpApi/controllers/RelationshipTemplatesController.ts
  src/modules/coreHttpApi/controllers/RelationshipsController.ts
  src/modules/coreHttpApi/controllers/TokensController.ts
Labels: dependencies

#436 Migrate from dependabot to renovate
  .github/dependabot.yml
  .github/renovate.json5
Labels: ci

#445 Tests do not run on node 24
  package-lock.json
  package.json
  packages/types/package.json
  packages/types/tsconfig.json
  test/tsconfig.json
  tsconfig.json
Labels: bug

#444 Add support for url references
  .dev/scripts/establishRelationshipAndSpamMessages.ts
  package-lock.json
  package.json
  packages/sdk/package.json
  packages/sdk/src/endpoints/FilesEndpoint.ts
  packages/sdk/src/endpoints/RelationshipTemplatesEndpoint.ts
  packages/sdk/src/endpoints/TokensEndpoint.ts
  packages/sdk/src/jsonSchemaDefinition.ts
  packages/sdk/src/types/files/ConnectorFile.ts
  packages/sdk/src/types/files/requests/CreateTokenQrCodeForFileRequest.ts
  packages/sdk/src/types/relationshipTemplates/ConnectorRelationshipTemplate.ts
  packages/sdk/src/types/relationshipTemplates/requests/CreateTokenQrCodeForOwnRelationshipTemplateRequest.ts
  packages/sdk/src/types/tokens/ConnectorToken.ts
  packages/sdk/tsconfig.json
  packages/types/package.json
  packages/types/src/QRCode.ts
  src/modules/coreHttpApi/controllers/FilesController.ts
  src/modules/coreHttpApi/controllers/RelationshipTemplatesController.ts
  src/modules/coreHttpApi/controllers/TokensController.ts
  src/modules/coreHttpApi/openapi.yml
  test/files.test.ts
  test/iqlquery.test.ts
  test/lib/QueryParamConditions.ts
  test/lib/testUtils.ts
  test/relationshipTemplates.test.ts
  test/relationships.test.ts
  test/tokens.test.ts
Labels: enhancement

#448 Upgrade to node 24
  .dev/Dockerfile.debug
  Dockerfile
Labels: dependencies

#456 Switch the default QR code format to the new one and remove the old one completely
  packages/sdk/src/endpoints/FilesEndpoint.ts
  packages/sdk/src/endpoints/RelationshipTemplatesEndpoint.ts
  packages/sdk/src/endpoints/TokensEndpoint.ts
  packages/sdk/src/types/files/requests/CreateTokenQrCodeForFileRequest.ts
  packages/sdk/src/types/relationshipTemplates/requests/CreateTokenQrCodeForOwnRelationshipTemplateRequest.ts
  src/modules/coreHttpApi/controllers/FilesController.ts
  src/modules/coreHttpApi/controllers/RelationshipTemplatesController.ts
  src/modules/coreHttpApi/controllers/TokensController.ts
  src/modules/coreHttpApi/openapi.yml
Labels: breaking-change

#459 Remove the file based changelog
  CHANGELOG.md
Labels: chore

#458 Simplify QR code generation
  packages/types/src/QRCode.ts
  packages/types/src/index.ts
  packages/types/src/infrastructure/httpServer/BaseController.ts
  src/modules/coreHttpApi/controllers/FilesController.ts
  src/modules/coreHttpApi/controllers/RelationshipTemplatesController.ts
  src/modules/coreHttpApi/controllers/TokensController.ts
Labels: refactoring

#460 Upgrade Runtime to version `7.0.0-alpha.26` and adapt to changes
  package-lock.json
  package.json
  packages/sdk/package.json
  packages/sdk/src/endpoints/AttributesEndpoint.ts
  packages/sdk/src/types/attributes/IQLQuery.ts
  packages/sdk/src/types/attributes/IdentityAttributeQuery.ts
  packages/sdk/src/types/attributes/RelationshipAttributeQuery.ts
  packages/sdk/src/types/attributes/ThirdPartyRelationshipAttributeQuery.ts
  packages/sdk/src/types/attributes/index.ts
  packages/sdk/src/types/attributes/requests/CanCreateRepositoryAttributeRequest.ts
  packages/sdk/src/types/attributes/requests/CreateRepositoryAttributeRequest.ts
  packages/sdk/src/types/attributes/requests/GetAttributesRequest.ts
  packages/sdk/src/types/attributes/requests/GetOwnRepositoryAttributesRequest.ts
  packages/sdk/src/types/attributes/requests/GetOwnSharedIdentityAttributesRequest.ts
  packages/sdk/src/types/attributes/requests/GetPeerSharedIdentityAttributesRequest.ts
  packages/sdk/src/types/attributes/requests/GetValidAttributesRequest.ts
  packages/sdk/src/types/attributes/requests/SucceedAttributeRequest.ts
  packages/sdk/src/types/files/ConnectorFile.ts
  packages/sdk/src/types/files/requests/UploadOwnFileRequest.ts
  packages/sdk/src/types/relationshipTemplates/ConnectorRelationshipTemplate.ts
  packages/sdk/src/types/relationships/ConnectorRelationship.ts
  packages/sdk/src/types/tokens/ConnectorToken.ts
  packages/types/package.json
  src/modules/coreHttpApi/controllers/AttributesController.ts
  src/modules/coreHttpApi/controllers/FilesController.ts
  src/modules/coreHttpApi/openapi.yml
  test/attributes.test.ts
  test/files.test.ts
  test/iqlquery.test.ts
  test/relationships.test.ts
Labels: breaking-change

#462 Upgrade backbone
  .dev/appsettings.override.json
  .dev/compose.backbone.env
  .dev/compose.backbone.yml
  .github/renovate.json5
  README_dev.md
  package.json
Labels: ci

#463 Handle the RelationshipTemplateAllocationsExhaustedExternalEvent
  package-lock.json
  package.json
  packages/sdk/package.json
  packages/types/package.json
Labels: bug

#464 Allow getting backbone announcements
  packages/sdk/src/ConnectorClient.ts
  packages/sdk/src/endpoints/AnnouncementsEndpoint.ts
  packages/sdk/src/endpoints/index.ts
  packages/sdk/src/types/announcements/ConnectorAnnouncement.ts
  packages/sdk/src/types/announcements/ConnectorAnnouncements.ts
  packages/sdk/src/types/announcements/index.ts
  packages/sdk/src/types/announcements/requests/GetAnnouncementsRequest.ts
  src/modules/coreHttpApi/controllers/AnnouncementsController.ts
  src/modules/coreHttpApi/openapi.yml
  test/announcements.test.ts
  test/lib/validation.ts
Labels: enhancement

#471 Remove outdated audit exclude
  .ci/runChecks.sh
Labels: chore

#473 Cli commands do not exit with 1 on error
  src/cli/BaseCommand.ts
  src/cli/commands/identity/status.ts
  src/cli/commands/identityDeletion/cancel.ts
  src/cli/commands/identityDeletion/init.ts
Labels: bug

#474 Bump runtime
  package-lock.json
  package.json
  packages/sdk/package.json
  packages/types/package.json
Labels: dependencies

#475 Audit fix
  package-lock.json
  package.json
Labels: dependencies

#476 Downgrade helm
  .github/workflows/publish.yml
  .github/workflows/test.yml
Labels: ci

#477 Deep queries are incorrectly implemented in the SDK
  packages/sdk/src/types/messages/requests/GetMessagesRequest.ts
  packages/sdk/src/types/relationships/requests/GetRelationshipsRequest.ts
  test/messages.test.ts
Labels: bug

#478 Upgrade helm again
  .github/workflows/publish.yml
  .github/workflows/test.yml
Labels: ci

#486 Peer is not required in shared Attribute getters of SDK
  packages/sdk/src/endpoints/AttributesEndpoint.ts
Labels: bug

#487 Enforce uniqueness of arrays and add support for `wasAutomaticallyDecided` in the request
  package-lock.json
  package.json
  packages/sdk/package.json
  packages/sdk/src/types/requests/ConnectorRequest.ts
  packages/types/package.json
  src/modules/coreHttpApi/controllers/IncomingRequestsController.ts
Labels: enhancement

#488 Update openapi.yml
  src/modules/coreHttpApi/openapi.yml
Labels: bug

#494 The SDK is not extensible
  packages/sdk/src/ConnectorClient.ts
Labels: bug
