Repository nmshd/connector, pull requests merged in 2025-01, with the labels that each got.

#308 Add identity deletion to the CLI
  src/ConnectorRuntime.ts
  src/cli/BaseCommand.ts
  src/cli/commands/identity/status.ts
  src/cli/commands/identityDeletion/cancel.ts
  src/cli/commands/identityDeletion/init.ts
  src/cli/commands/index.ts
  src/index.ts
  test/modules/cli/identity/identityStatus.test.ts
  test/modules/cli/identityDeletion/identityDeletion.test.ts
  test/modules/cli/setup.ts
  tsconfig.json
Labels: enhancement

#339 Proper Wording in Deletion CLI
  src/cli/commands/identity/status.ts
  test/modules/cli/identity/identityStatus.test.ts
Labels: bug

#340 SDK CorrelationID Support
  packages/sdk/src/ConnectorClient.ts
  test/correlationId.test.ts
Labels: enhancement

#341 Prettier Setup
  .github/PULL_REQUEST_TEMPLATE.md
  .prettierignore
  CHANGELOG.md
  README_dev.md
  package.json
  packages/sdk/README.md
Labels: chore

#342 Remove FerretDB Pipeline
  .dev/appsettings.override.json
  .dev/compose.backbone.env
  .github/workflows/test.yml
Labels: chore

#347 DatawalletSynchronizedEvent is not anymore emitted in the connector
  package-lock.json
  package.json
  packages/sdk/package.json
  test/attributes.test.ts
  test/identityMetadata.test.ts
  test/iqlquery.test.ts
  test/lib/testUtils.ts
  test/lib/validation.ts
Labels: bug

#349 Allow `lengthOfGracePeriodInDays` to be set in debug API
  src/modules/coreHttpApi/debug-controllers/IdentityDeletionProcessController.ts
Labels: enhancement

#351 Optional properties specified as required in OpenAPI
  src/modules/coreHttpApi/openapi.yml
  test/files.test.ts
Labels: bug

#354 NodeJS alpine is causing DNS lookup issues
  Dockerfile
Labels: bug

#355 Bump libs
  package-lock.json
  package.json
  packages/sdk/package.json
  src/modules/sse/SseModule.ts
Labels: dependencies

#356 Arm64 images containing amd tini version
  Dockerfile
Labels: bug

#357 Healthcheck is not executing
  Dockerfile
  src/healthcheck.ts
Labels: bug
