Repository nmshd/connector, pull requests merged in 2025-04, with the labels that each got.

#410 Add deleteFile endpoint
  packages/sdk/src/endpoints/FilesEndpoint.ts
  src/modules/coreHttpApi/controllers/FilesController.ts
  src/modules/coreHttpApi/openapi.yml
  test/files.test.ts
  test/spec.test.ts
Labels: enhancement

#414 Add optional link text to consents
  package-lock.json
  package.json
  packages/sdk/package.json
  packages/types/package.json
Labels: enhancement

#416 bump runtime
  package-lock.json
  package.json
  packages/sdk/package.json
  packages/types/package.json
Labels: dependencies

#420 Add FormFieldRequestItem
  package-lock.json
  package.json
  packages/sdk/package.json
  packages/types/package.json
Labels: enhancement

#421 Allow longer tags
  package-lock.json
  package.json
  packages/sdk/package.json
  packages/types/package.json
Labels: enhancement

#426 Add support for semi-individualized passwords
  package-lock.json
  package.json
  packages/sdk/package.json
  packages/sdk/src/types/files/requests/CreateTokenForFileRequest.ts
  packages/sdk/src/types/files/requests/CreateTokenQrCodeForFileRequest.ts
  packages/sdk/src/types/relationshipTemplates/ConnectorRelationshipTemplate.ts
  packages/sdk/src/types/relationshipTemplates/requests/CreateOwnRelationshipTemplateRequest.ts
  packages/sdk/src/types/relationshipTemplates/requests/CreateTokenForOwnRelationshipTemplateRequest.ts
  packages/sdk/src/types/relationshipTemplates/requests/CreateTokenQrCodeForOwnRelationshipTemplateRequest.ts
  packages/sdk/src/types/relationshipTemplates/requests/GetOwnRelationshipTemplatesRequest.ts
  packages/sdk/src/types/relationshipTemplates/requests/GetPeerRelationshipTemplatesRequest.ts
  packages/sdk/src/types/relationshipTemplates/requests/GetRelationshipTemplatesRequest.ts
  packages/sdk/src/types/tokens/ConnectorToken.ts
  packages/sdk/src/types/tokens/requests/CreateOwnTokenRequest.ts
  packages/sdk/src/types/tokens/requests/GetOwnTokensRequest.ts
  packages/sdk/src/types/tokens/requests/GetPeerTokensRequest.ts
  packages/types/package.json
  src/modules/coreHttpApi/openapi.yml
  test/files.test.ts
  test/lib/testUtils.ts
  test/relationshipTemplates.test.ts
  test/tokens.test.ts
Labels: enhancement, wip

#428 Add ApiKey support to webhooks module
  src/modules/webhooks/ConfigParser.ts
  src/modules/webhooks/WebhooksModuleConfiguration.ts
  src/modules/webhooks/authentication/ApiKeyAuthenticationProvider.ts
  src/modules/webhooks/authentication/index.ts
Labels: enhancement

#429 Bump Runtime
  package-lock.json
  package.json
  packages/sdk/package.json
  packages/types/package.json
  src/modules/coreHttpApi/controllers/RelationshipTemplatesController.ts
  src/modules/coreHttpApi/openapi.yml
Labels: dependencies
