Repository nmshd/connector, pull requests merged in 2025-03, with the labels that each got.

#379 Only log to console by default
  Dockerfile
  src/createConnectorConfig.ts
Labels: bug

#382 publish pipeline does not publish all npm packages
  .ci/publishNpm.sh
Labels: ci

#383 Publish zipped connector fails because of npm package missing
  .ci/buildConnectorZip.sh
  .ci/publishNpm.sh
  .github/workflows/publish.yml
Labels: ci

#388 Change dependabot npm updates reviewers
  .github/dependabot.yml
  package-lock.json
  packages/types/package.json
Labels: ci

#389 Starting a connector without a baseUrl configured throws a confusing error
  src/jsonSchemas/connectorConfig.json
Labels: bug

#390 Bump backbone to 6.33.0
  .dev/appsettings.override.json
  .dev/compose.backbone.env
  .dev/compose.backbone.yml
Labels: dependencies

#394 Bump backbone to 6.34.2
  .dev/appsettings.override.json
  .dev/compose.backbone.env
Labels: dependencies

#395 Simplify boolean conversion
  package-lock.json
  package.json
  src/modules/coreHttpApi/controllers/AttributesController.ts
Labels: refactoring

#396 Upgrade runtime to 6.32.0
  package-lock.json
  package.json
  packages/sdk/package.json
  packages/types/package.json
  src/modules/sse/SseModule.ts
  test/iqlquery.test.ts
Labels: enhancement

#397 Local backbone does not start
  .dev/compose.backbone.yml
Labels: chore

#398 Standardized capitalization of terms
  .dev/.env.example
  .dev/.env.local
  .dev/scripts/linkRuntime.sh
  .github/ISSUE_TEMPLATE/config.yml
  .github/workflows/publish.yml
  README.md
  README_dev.md
  helmChart/Chart.yaml
  package.json
  packages/sdk/README.md
  packages/sdk/package.json
  packages/sdk/src/endpoints/Endpoint.ts
  packages/types/README.md
  packages/types/package.json
  src/ConnectorRuntime.ts
  src/HealthChecker.ts
  src/cli/commands/identity/status.ts
  src/cli/commands/identityDeletion/cancel.ts
  src/cli/commands/identityDeletion/init.ts
  src/cli/commands/startConnector.ts
  src/infrastructure/httpServer/middlewares/genericErrorHandler.ts
  src/modules/coreHttpApi/CoreHttpApiModule.ts
  src/modules/coreHttpApi/openapi.yml
Labels: chore

#400 Race condition occurs when auto-decomposing a deletion proposed relationship
  package-lock.json
  package.json
  packages/sdk/package.json
  packages/types/package.json
  src/modules/autoDecomposeDeletionProposedRelationships/AutoDecomposeDeletionProposedRelationshipsModule.ts
Labels: bug

#401 Move more classes to shared types
  .github/settings.yml
  package-lock.json
  packages/types/package.json
  packages/types/src/infrastructure/httpServer/BaseController.ts
  packages/types/src/infrastructure/httpServer/common/Mimetype.ts
  packages/types/src/infrastructure/httpServer/common/index.ts
  packages/types/src/infrastructure/httpServer/index.ts
  src/modules/coreHttpApi/controllers/AccountController.ts
  src/modules/coreHttpApi/controllers/AttributesController.ts
  src/modules/coreHttpApi/controllers/ChallengesController.ts
  src/modules/coreHttpApi/controllers/FilesController.ts
  src/modules/coreHttpApi/controllers/IdentityMetadataController.ts
  src/modules/coreHttpApi/controllers/IncomingRequestsController.ts
  src/modules/coreHttpApi/controllers/MessagesController.ts
  src/modules/coreHttpApi/controllers/OutgoingRequestsController.ts
  src/modules/coreHttpApi/controllers/RelationshipTemplatesController.ts
  src/modules/coreHttpApi/controllers/RelationshipsController.ts
  src/modules/coreHttpApi/controllers/TokensController.ts
  src/modules/coreHttpApi/debug-controllers/IdentityDeletionProcessController.ts
Labels: enhancement

#404 Simplify writing modules
  package-lock.json
  packages/types/package.json
  packages/types/src/AbstractConnectorRuntime.ts
  src/ConnectorRuntime.ts
  src/createConnectorConfig.ts
Labels: enhancement

#405 Expose database information in connector runtime config
  packages/types/src/AbstractConnectorRuntime.ts
Labels: bug

#407 Bundled config is not found on windows
  src/createConnectorConfig.ts
Labels: bug
